repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: check-added-large-files
        - id: check-executables-have-shebangs
        - id: check-shebang-scripts-are-executable
        - id: double-quote-string-fixer
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          exclude: .*_encrypted.*
          args:
            - "--allow-multiple-documents"
        - id: pretty-format-json
          exclude: .*_encrypted.json
          args:
            - "--no-sort-keys"
            - "--no-ensure-ascii"
            - "--autofix"
        - id: check-json

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.1.0 # Get the latest from: https://github.com/tofuutils/pre-commit-opentofu/releases
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
      - id: tofu_tflint
        args:
          - --args=--disable-rule=terraform_unused_declarations
      - id: tofu_docs
        args:
          - --args=--lockfile=true
          - --hook-config=--path-to-file=README.md # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --hook-config=--use-standard-markers=true # Boolean. Defaults in v1.x to false. Set to true for compatibility with terraform-docs

      - id: tofu_trivy
        args:
          - --args=--config __GIT_WORKING_DIR__trivy.yaml
          - --args=--severity=HIGH
          - --args=--tf-exclude-downloaded-modules
          - --args=--skip-dirs "**/.terraform/**/*"
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.194.0
    hooks:
      - id: renovate-config-validator
